### ISSUE TITLE
chroot: failed to run command '/bin/bash': Exec format error when make build-ubuntu-rootfs

### ISSUE THREAD

**Issue by shirubax** [tsukumijima/QuaStation-Ubuntu#1]
Kernelのビルドは問題なくできますが、ルートファイルシステムはこのようのエラーが出ます。
shiruba@kaminari:~/dev/QuaStation-Ubuntu$ make build-ubuntu-rootfs
docker run --privileged --rm -i -t -h QuaStation -v `pwd`:/build/ quastation-ubuntu /bin/bash -c 'make build-ubuntu-rootfs-in-container'
--------------------------------------------------------------------------------
Building Ubuntu 20.04 LTS rootfs...
--------------------------------------------------------------------------------
--2023-01-21 19:00:35--  http://ftp.jaist.ac.jp/pub/Linux/ubuntu-cdimage/ubuntu-base/releases/20.04/release/ubuntu-base-20.04.4-base-arm64.tar.gz
Resolving ftp.jaist.ac.jp (ftp.jaist.ac.jp)... 150.65.7.130, 2001:df0:2ed:feed::feed
Connecting to ftp.jaist.ac.jp (ftp.jaist.ac.jp)|150.65.7.130|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26228459 (25M) [application/x-gzip]
Saving to: 'ubuntu-base-20.04.4-base-arm64.tar.gz'

ubuntu-base-20.04.4 100%[===================>]  25.01M  12.0MB/s    in 2.1s    

2023-01-21 19:00:37 (12.0 MB/s) - 'ubuntu-base-20.04.4-base-arm64.tar.gz' saved [26228459/26228459]
bin
boot/
dev/
etc/
etc/.pwd.lock
etc/adduser.conf
...
**chroot: failed to run command '/bin/bash': Exec format error**
--------------------------------------------------------------------------------
Ubuntu 20.04 LTS rootfs build is completed.
--------------------------------------------------------------------------------

**Comment by tsukumijima** [comment]
まず、このようなマニアックなリポジトリを利用される方がいることに驚いています。

もう長いこと試していないのでわからないですが、もしかするとホスト側に qemu-user-static をインストールすることで改善されることがあるかもしれません。
このエラーは arm64 向けの bash バイナリが x86_64 から直接実行できないため発生しているものと思われます。本来であればビルド用の Docker コンテナに qemu-user-static が入っているので、それを使い arm64 バイナリも実行できるようになるはずなのですが…

**Comment by shirubax** [comment]
> まず、このようなマニアックなリポジトリを利用される方がいることに驚いています。
> 
> もう長いこと試していないのでわからないですが、もしかするとホスト側に qemu-user-static をインストールすることで改善されることがあるかもしれません。
> このエラーは arm64 向けの bash バイナリが x86_64 から直接実行できないため発生しているものと思われます。本来であればビルド用の Docker コンテナに qemu-user-static が入っているので、それを使い arm64 バイナリも実行できるようになるはずなのですが…

返事、ありがとうございます。

全然使っています。というか、使う予定です。
BPIのkernelを自分でコンパイルして、今でも使っていますが、デバイスツリーは詳しくないので電源ボタンなどは機能しない。

マニアックかというと…QuaStationを２０代ほど集まっていて、NASとして使っています。

今はほぼ標準のUbuntu ２０を使っていますのでこのプロジェクトを見つけて、とても嬉しいです。

エラーメッセージを見て、ARMバイリーをchrootで実行しようとしてるだろうと思いましたが、スクリプトの作成者ならすぐでも解決方法が分かると思いました。

一応qemuの方法を試してみます。
それでもだめなら、m2 macのlinux vmで試してみます。

アイデアですけど、kernelとrooftのバイナリーも提供したら便利かもしれない。

**Comment by tsukumijima** [comment]
なるほど NAS 用途ですか…。たしかに 1TB HDD が入っている上にメルカリなどで投げ売りされているので、用途としてはいいかもしれませんね。スペックはラズパイ3程度ですが、NAS 程度であれば問題ないでしょうし。
ただ Wi-Fi しかない上に Wi-Fi がちょっと不安定な節があるので、別途 USB-LAN を買う必要があるデメリットはありますが…。

一応、手元の環境でビルドした成果物が残っていたので、それを共有しておきます。
もともとビルド自体にもかなり時間がかかるので、よろしければ。
https://github.com/tsukumijima/QuaStation-Ubuntu/releases/tag/v1.0.0

**Comment by shirubax** [comment]
返事、ありがとうございます。
そうですね、QuaStationは送料込み2000円前後で購入できる場合も多いですのでコストパフォマンスはとても良いと思います。
プラス1000円でUSB3のギガビットイーサネットとUSB　Boot Driveを入れても3000円〜4000円で完成。

ちなみに、英語になりますが確認済のUSB3 Ethernetの話は下記：
https://shiruba-technology.blogspot.com/2021/07/qua-station-kernel-build-and-install.html

qemu-user-static をインストールしてからビルドは進んでいます！
念の為、上記のリンクのusbflash.tar.xzもダウンロードしました。
ありがとうございます。

**Comment by tsukumijima** [comment]
> qemu-user-static をインストールしてからビルドは進んでいます！

ビルドを進められているようでよかったです。
Docker 環境で rootfs を構築しているはずなのにホスト側にも入れないといけないのがちょっと腑に落ちないですが、Docker はホスト側のリソースをある程度共有しているので、その関係なのかもしれません。
build_ubuntu_rootfs.sh には録画サーバー用途のためのソフトを色々入れていたりするので、もし不要であれば適宜コメントアウトしていただければ。

また、mt999a さんが USB 3.0 を有効化しスループットを向上させた 4.9.119 カーネル (QuaStation-Kernel-BPi) の [フォーク](https://github.com/mt999a/QuaStation-Kernel-BPi/tree/feature/enable_usb3_develop) を開発されています。
私自身は Qua Station はもうほとんど触っていないので確認できていないのですが、もしご興味があるようでしたら使ってみても良いかもしれません（ただしデバイスツリーに変更が入っているので、一部機能が動かなくなってしまうことはあるかも）。

**Comment by shirubax** [comment]
一応、qemu-user-staticを活用してビルドは無事にできましたのでCloseさせていただきます。ありがとうございます
mt999aさんの変更はマージする予定ないですか。
（たくさんの質問がありますが正しい場所はここではないでしょう）。

**Comment by tsukumijima** [comment]
> mt999aさんの変更はマージする予定ないですか。

私はデバイスツリーに関してはまったくと言っていいほど詳しくありませんし、Linux カーネルにも詳しくありません。
これらのリポジトリはそうした中で私が執念で数カ月間試行錯誤してなんとかうまく行ったものを上げているだけで、どこかをいじってしまったらすぐ壊れてしまうのではないか、という怖さもあります（特にデバイスツリー）。

動作確認ができればマージしても良いとは思っているのですが、もう Qua Station を触ることに飽きてしまったのもあって時間が取れないでいます。もしそちらで動作確認していただけるなら（マージしたカーネルでデグレードが発生していなければ）マージしますが…。

**Comment by shirubax** [comment]
昨日新しいQuaStation届きましたので、m999aさんのKernelとビルドしたtsukumijima様のUbuntuを入れて検証します。
すでに分割して、只今コピー中です。
（その上、LTEカードをmSATA型SSDとの交換も検証します。）
後ほど報告させていただきます。

**Comment by shirubax** [comment]
m999aさんのKernelをそのままを使うと問題ないようです。
例えば、LEDもGPIOもWiFiも問題なく使えます。
ただ、僕に対して使い物にならないことがあって（BTRFSはサポートされていない）
それを解決するためにmake configを行って、BTFRSをオンにして再ビルドを行いました。
コンパイルも問題ないし、QuaStationにコピーしたら起動ができますが…
WiFiが見えなくなり、ボタン押してもスクリプトも走らないのでおそらくGPIOも壊した。
make configの問題と思って、直接にrtd1295_quastation_defconfigを手で触っても同じ問題が発生します。
つまり、設定を変更したら、変更した設定と関係ないところが影響されているようです。
おそらくmt999aさんのフォーク独自問題ではないですのでツクミジマさんのBPi Kernelで再現してみます。
